#spring.application.name=term_paper
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rc1b-2xmunoaqhipsaggs.mdb.yandexcloud.net:3306/nikitango?useSSL=true
    username: nikitango
    password: nikitango

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10
